# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 824a46f10eda8a0ddb646dcbedf5d5525e24bfdf83ea7e008749c8d4a51fc1f6c2717bff6f564df679efa38e0f57c9fd8c8a587b7d8b224db5f862c01d6fceea

test:
  secret_key_base: 7afca96ca33e3b44f728d82eff3ffb4137d2f51f88482db4176e61f3da3c695c0f0d22f4d71863e712660d52ffdf455f541a3b29205381b7bc1fcb351ff88040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
